apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
  namespace: longhorn-system
type: Opaque
data:
  AWS_ACCESS_KEY_ID: YWRtaW5pc3RyYXRvcg==
  AWS_SECRET_ACCESS_KEY: RXNwb2lyMTIzLg==
  AWS_ENDPOINTS: aHR0cDovLzM3LjM1LjAuMjMxOjkwMDA=
