---

- name: Deploy-Agent
  hosts: all
  become: yes
  become_method: sudo
  gather_facts: true
    
  tasks :
  - name: Ajout du zabbix dépot Zabbix 
    when: inventory_hostname in groups['ubuntu64Guest']
    apt:
      update_cache: yes
      deb: https://repo.zabbix.com/zabbix/5.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_5.0-1%2Bfocal_all.deb
      state: present

  - name: installation de l'agent Zabbix
    when: inventory_hostname in groups['ubuntu64Guest']
    apt:
      update_cache: yes
      name: zabbix-agent
      state: present

  - name: Template Zabbix agent Conf
    template:
      src: Templates/zabbix_agentd_conf.j2
      dest: /etc/zabbix/zabbix_agentd.conf

  - name: enable & start Zabbix-Agent
    systemd:
      name: zabbix-agent
      daemon_reload: yes
      state: restarted
      enabled: True